### ISSUE TITLE
Sidi Ahmad alawi

### ISSUE THREAD

**Issue by Gaggags** [MalikiMadhab/malikimadhab.github.io#1]
আহমাদ আল-আলাভী আল মালেকী রহমাতুল্লাহি আলাইহি 

আবু আল-আব্বাস আহমেদ ইবনে মুসতাফা ইবনে আলিউই , যিনি আল-আলাউই আল-মুস্তাঘানিমি নামে পরিচিত ছিলেন। তিনি নিজস্ব সুফি তরিকা প্রতিষ্ঠা করেছিলেন, তাকে আলাউইয়া বলা হয় ।

শায়েখ আহমাদ আল-আলাউই 1869 সালে মোস্তাগানেমে জন্মগ্রহণ করেন । তিনি তার বাবার কাছে বাড়িতেই শিক্ষা গ্রহণ করেন। 1886 সালে পিতার মৃত্যুর সময় থেকে 1894 সাল পর্যন্ত তিনি মোস্তাগানেমে কাজ করেছিলেন।

1894 সালে, তিনি মরক্কো ভ্রমণ করেন এবং 15 বছর ধরে দারকাউইতে শায়েখ মুহাম্মাদ আল-বুজিদিকে অনুসরণ করেন। 1909 সালে আল-বুজিদির মৃত্যুর পর, শায়েখ আল-আলাউই মোস্তাগানেমে ফিরে আসেন, যেখানে তিনি প্রথমে দাওয়া ছড়িয়ে দেন এবং তারপরে (1914 সালে) তিনি আলাউই তরীকা প্রতিষ্ঠা করেন, যাকে রাসুল (সাল্লাল্লাহু আলাইহি ওয়া আলিহী ওয়াসাল্লাম) ওনার জামাতা আলীর সম্মানে আলাউইয়া বলা হয় । যিনি একটি দর্শনে তাকে দেখা দিয়েছিলেন এবং তার নতুন আদেশের জন্য তাকে এই নামটি দিয়েছিলেন।

একজন ক্লাসিক সুফি শাইখ হওয়ার পাশাপাশি, আল-আলাউই আধুনিক পদ্ধতি ব্যবহার করে আধুনিক আলজেরিয়ানদের সমস্যার সমাধান করেছিলেন। 

তিনি প্রতিষ্ঠিত সুফি বিষয়ের উপর কবিতা এবং বই লিখেছেন এবং 1912 সালে দুটি সাপ্তাহিক সংবাদপত্র, স্বল্পকালীন লিসান আল-দিন এবং আল-বালাঘ আল-জাজাইরি (আলজেরিয়ান) প্রতিষ্ঠা ও পরিচালনা করেছিলেন।

![Screenshot_20231112-174331.jpg](https://github.com/MalikiMadhab/malikimadhab.github.io/assets/150575820/a251fc18-b4e2-4028-87cb-5c49aee6f34b).md

**Comment by MalikiMadhab** [comment]
ভাই, আপনি ইস্যু ক্রিয়েট করেছেন। আপনাকে ফাইল ক্রিয়েট করতে হবে। আমি আপনার জন্য করে দিয়েছি ফাইল [দেখুন](https://github.com/MalikiMadhab/malikimadhab.github.io/blob/main/ahmad-al-alavi.md)
ফাইল মোতাবেক ওয়েবপেজ এখানে দেখুন https://malikimadhab.github.io/ahmad-al-alavi
